apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clean-core.fullname" . }}-secret
type: Opaque
stringData:
  CLEAN_CORE_SERVICE_TOKEN: {{ .Values.secret.serviceToken | quote }}
  CLEAN_CORE_DATABASE_URL: {{ .Values.secret.databaseURL | quote }}
  CLEAN_CORE_MODEL_BASE_URL: {{ .Values.secret.modelBaseURL | quote }}
  CLEAN_CORE_MODEL_API_KEY: {{ .Values.secret.modelAPIKey | quote }}
  CLEAN_CORE_MODEL_NAME: {{ .Values.secret.modelName | quote }}
  CLEAN_CORE_EXTERNAL_BRIDGE_BASE_URL: {{ .Values.secret.externalBridgeBaseURL | quote }}
  CLEAN_CORE_EXTERNAL_BRIDGE_TOKEN: {{ .Values.secret.externalBridgeToken | quote }}
