// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	TenantID     string             `json:"tenant_id"`
	ActorType    string             `json:"actor_type"`
	ActorID      string             `json:"actor_id"`
	RequestID    string             `json:"request_id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	EventType    string             `json:"event_type"`
	MetadataJson []byte             `json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	ProducerApiKeyID pgtype.UUID        `json:"producer_api_key_id"`
	IdempotencyKey   string             `json:"idempotency_key"`
	RequestHash      string             `json:"request_hash"`
	StatusCode       int32              `json:"status_code"`
	ResponseJson     []byte             `json:"response_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	TaskTypeID           pgtype.UUID        `json:"task_type_id"`
	TaskKey              string             `json:"task_key"`
	Source               string             `json:"source"`
	Status               string             `json:"status"`
	Priority             int32              `json:"priority"`
	InputJson            []byte             `json:"input_json"`
	EncryptedPayloadJson []byte             `json:"encrypted_payload_json"`
	ResultJson           []byte             `json:"result_json"`
	EncryptedResultJson  []byte             `json:"encrypted_result_json"`
	Progress             int32              `json:"progress"`
	RunAt                pgtype.Timestamptz `json:"run_at"`
	AttemptCount         int32              `json:"attempt_count"`
	MaxRetry             int32              `json:"max_retry"`
	LeaseSec             int32              `json:"lease_sec"`
	TimeoutSec           int32              `json:"timeout_sec"`
	WorkerPoolID         pgtype.UUID        `json:"worker_pool_id"`
	RequiredWorkerTags   []string           `json:"required_worker_tags"`
	CancelRequested      bool               `json:"cancel_requested"`
	ErrorCode            pgtype.Text        `json:"error_code"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	OutputSchemaJson     []byte             `json:"output_schema_json"`
	StorageEnabled       bool               `json:"storage_enabled"`
	AllowEncryptedResult bool               `json:"allow_encrypted_result"`
	TaskTypeRevision     int32              `json:"task_type_revision"`
	ExternalUserHash     string             `json:"external_user_hash"`
}

type JobAsset struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	JobID          pgtype.UUID        `json:"job_id"`
	WorkerJobID    pgtype.UUID        `json:"worker_job_id"`
	Direction      string             `json:"direction"`
	Kind           string             `json:"kind"`
	Uri            string             `json:"uri"`
	Name           string             `json:"name"`
	ContentType    string             `json:"content_type"`
	ByteSize       pgtype.Int8        `json:"byte_size"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	MetadataJson   []byte             `json:"metadata_json"`
	RetentionUntil pgtype.Timestamptz `json:"retention_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type JobEvent struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	JobID        pgtype.UUID        `json:"job_id"`
	WorkerJobID  pgtype.UUID        `json:"worker_job_id"`
	EventType    string             `json:"event_type"`
	Message      string             `json:"message"`
	MetadataJson []byte             `json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type JobLog struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	JobID        pgtype.UUID        `json:"job_id"`
	WorkerJobID  pgtype.UUID        `json:"worker_job_id"`
	Level        string             `json:"level"`
	Message      string             `json:"message"`
	MetadataJson []byte             `json:"metadata_json"`
	MessageBytes int32              `json:"message_bytes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ProducerApiKey struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Name               string             `json:"name"`
	KeyHash            string             `json:"key_hash"`
	Scopes             []string           `json:"scopes"`
	RateLimitPerMinute int32              `json:"rate_limit_per_minute"`
	Status             string             `json:"status"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	AllowedTaskKeys    []string           `json:"allowed_task_keys"`
}

type ProducerCallbackDelivery struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	CallbackID         pgtype.UUID        `json:"callback_id"`
	JobID              pgtype.UUID        `json:"job_id"`
	EventType          string             `json:"event_type"`
	AttemptNumber      int32              `json:"attempt_number"`
	Status             string             `json:"status"`
	CallbackUrl        string             `json:"callback_url"`
	StatusCode         pgtype.Int4        `json:"status_code"`
	Error              pgtype.Text        `json:"error"`
	ResponseBodySample pgtype.Text        `json:"response_body_sample"`
	DurationMs         int64              `json:"duration_ms"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ProducerJobCallback struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	JobID             pgtype.UUID        `json:"job_id"`
	Source            string             `json:"source"`
	EventType         string             `json:"event_type"`
	ProducerApiKeyID  pgtype.UUID        `json:"producer_api_key_id"`
	EndpointID        pgtype.UUID        `json:"endpoint_id"`
	CallbackUrl       string             `json:"callback_url"`
	SigningSecret     string             `json:"signing_secret"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	LastStatusCode    pgtype.Int4        `json:"last_status_code"`
	LastError         pgtype.Text        `json:"last_error"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ReadyAt           pgtype.Timestamptz `json:"ready_at"`
	TerminalJobStatus pgtype.Text        `json:"terminal_job_status"`
}

type ProducerKeyAuditEvent struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	ProducerApiKeyID pgtype.UUID        `json:"producer_api_key_id"`
	EventType        string             `json:"event_type"`
	ActorType        string             `json:"actor_type"`
	ActorID          string             `json:"actor_id"`
	MetadataJson     []byte             `json:"metadata_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ProducerRateLimit struct {
	ProducerApiKeyID pgtype.UUID        `json:"producer_api_key_id"`
	WindowStart      pgtype.Timestamptz `json:"window_start"`
	RequestCount     int32              `json:"request_count"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProducerUsageDailyByKey struct {
	ProjectID          pgtype.UUID        `json:"project_id"`
	ProducerApiKeyID   pgtype.UUID        `json:"producer_api_key_id"`
	UsageDate          pgtype.Date        `json:"usage_date"`
	JobsCreated        int32              `json:"jobs_created"`
	CallbacksDelivered int32              `json:"callbacks_delivered"`
	CallbacksFailed    int32              `json:"callbacks_failed"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ProducerUsageDailyByProject struct {
	ProjectID          pgtype.UUID        `json:"project_id"`
	UsageDate          pgtype.Date        `json:"usage_date"`
	JobsCreated        int32              `json:"jobs_created"`
	CallbacksDelivered int32              `json:"callbacks_delivered"`
	CallbacksFailed    int32              `json:"callbacks_failed"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ProducerWebhookEndpoint struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	SigningSecret string             `json:"signing_secret"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ProducerWebhookSubscription struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	EndpointID pgtype.UUID        `json:"endpoint_id"`
	EventTypes []string           `json:"event_types"`
	TaskKeys   []string           `json:"task_keys"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        string             `json:"tenant_id"`
	CreatedByUserID string             `json:"created_by_user_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Status          string             `json:"status"`
	SettingsJson    []byte             `json:"settings_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProjectJobFailedMinuteStat struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Shard       int16              `json:"shard"`
	FailedJobs  int64              `json:"failed_jobs"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectJobStatusStat struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	StatusGroup string             `json:"status_group"`
	Shard       int16              `json:"shard"`
	JobCount    int64              `json:"job_count"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectQuota struct {
	ProjectID                  pgtype.UUID        `json:"project_id"`
	MaxWaitingJobs             pgtype.Int4        `json:"max_waiting_jobs"`
	MaxRunningJobs             pgtype.Int4        `json:"max_running_jobs"`
	MaxMonthlyJobsCreated      pgtype.Int4        `json:"max_monthly_jobs_created"`
	MaxMonthlyWorkerPulls      pgtype.Int4        `json:"max_monthly_worker_pulls"`
	MaxMonthlyCallbackAttempts pgtype.Int4        `json:"max_monthly_callback_attempts"`
	MaxMonthlyAssetRefs        pgtype.Int4        `json:"max_monthly_asset_refs"`
	Status                     string             `json:"status"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeHeartbeat struct {
	Name                string             `json:"name"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastRunAt           pgtype.Timestamptz `json:"last_run_at"`
	LastCount           int64              `json:"last_count"`
	LastError           string             `json:"last_error"`
	ExpectedIntervalSec int64              `json:"expected_interval_sec"`
}

type Schedule struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	TaskTypeID           pgtype.UUID        `json:"task_type_id"`
	TaskKey              string             `json:"task_key"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	Status               string             `json:"status"`
	CronExpr             string             `json:"cron_expr"`
	Timezone             string             `json:"timezone"`
	InputJson            []byte             `json:"input_json"`
	EncryptedPayloadJson []byte             `json:"encrypted_payload_json"`
	Priority             int32              `json:"priority"`
	MaxFireCount         pgtype.Int4        `json:"max_fire_count"`
	FiredCount           int32              `json:"fired_count"`
	NextRunAt            pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt            pgtype.Timestamptz `json:"last_run_at"`
	LastJobID            pgtype.UUID        `json:"last_job_id"`
	MetadataJson         []byte             `json:"metadata_json"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TaskType struct {
	ID                    pgtype.UUID        `json:"id"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	TaskKey               string             `json:"task_key"`
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	InputSchemaJson       []byte             `json:"input_schema_json"`
	OutputSchemaJson      []byte             `json:"output_schema_json"`
	RequiredWorkerTags    []string           `json:"required_worker_tags"`
	WorkerPoolID          pgtype.UUID        `json:"worker_pool_id"`
	MaxConcurrentJobs     pgtype.Int4        `json:"max_concurrent_jobs"`
	MaxQueueLength        pgtype.Int4        `json:"max_queue_length"`
	MaxJobsPerPull        int32              `json:"max_jobs_per_pull"`
	LeaseSec              int32              `json:"lease_sec"`
	TimeoutSec            int32              `json:"timeout_sec"`
	MaxRetry              int32              `json:"max_retry"`
	ProducerEnabled       bool               `json:"producer_enabled"`
	CallbacksEnabled      bool               `json:"callbacks_enabled"`
	SchedulerEnabled      bool               `json:"scheduler_enabled"`
	StorageEnabled        bool               `json:"storage_enabled"`
	AllowEncryptedPayload bool               `json:"allow_encrypted_payload"`
	AllowEncryptedResult  bool               `json:"allow_encrypted_result"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	RetryBackoffSec       int32              `json:"retry_backoff_sec"`
	ContractRevision      int32              `json:"contract_revision"`
}

type UsageDailyCounter struct {
	ProjectID  pgtype.UUID        `json:"project_id"`
	UsageDate  pgtype.Date        `json:"usage_date"`
	Metric     string             `json:"metric"`
	Quantity   int64              `json:"quantity"`
	Bytes      int64              `json:"bytes"`
	DurationMs int64              `json:"duration_ms"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UsageEvent struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	JobID       pgtype.UUID        `json:"job_id"`
	WorkerJobID pgtype.UUID        `json:"worker_job_id"`
	EventType   string             `json:"event_type"`
	JobStatus   string             `json:"job_status"`
	Attempt     int32              `json:"attempt"`
	InputBytes  int32              `json:"input_bytes"`
	ResultBytes int32              `json:"result_bytes"`
	LogBytes    int32              `json:"log_bytes"`
	DurationMs  int64              `json:"duration_ms"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Worker struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Name               string             `json:"name"`
	Version            string             `json:"version"`
	Environment        string             `json:"environment"`
	Tags               []string           `json:"tags"`
	WorkerPoolID       pgtype.UUID        `json:"worker_pool_id"`
	Status             string             `json:"status"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	CurrentRunningJobs int32              `json:"current_running_jobs"`
	MaxConcurrentJobs  int32              `json:"max_concurrent_jobs"`
	MetadataJson       []byte             `json:"metadata_json"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	InstanceID         string             `json:"instance_id"`
}

type WorkerJob struct {
	ID            pgtype.UUID        `json:"id"`
	JobID         pgtype.UUID        `json:"job_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	TaskTypeID    pgtype.UUID        `json:"task_type_id"`
	WorkerID      pgtype.UUID        `json:"worker_id"`
	WorkerTokenID pgtype.UUID        `json:"worker_token_id"`
	WorkerPoolID  pgtype.UUID        `json:"worker_pool_id"`
	Status        string             `json:"status"`
	Attempt       int32              `json:"attempt"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WorkerPool struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Name                string             `json:"name"`
	Key                 string             `json:"key"`
	Description         string             `json:"description"`
	MaxConcurrentJobs   pgtype.Int4        `json:"max_concurrent_jobs"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ResourceProfileJson []byte             `json:"resource_profile_json"`
}

type WorkerRateLimit struct {
	WorkerTokenID pgtype.UUID        `json:"worker_token_id"`
	WindowStart   pgtype.Timestamptz `json:"window_start"`
	RequestCount  int32              `json:"request_count"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Bucket        string             `json:"bucket"`
}

type WorkerToken struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	Name                 string             `json:"name"`
	TokenHash            string             `json:"token_hash"`
	Scopes               []string           `json:"scopes"`
	AllowedTaskKeys      []string           `json:"allowed_task_keys"`
	AllowedWorkerPoolIds []pgtype.UUID      `json:"allowed_worker_pool_ids"`
	AllowedTags          []string           `json:"allowed_tags"`
	MaxConcurrentJobs    pgtype.Int4        `json:"max_concurrent_jobs"`
	Status               string             `json:"status"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}
