// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTaskType(ctx context.Context, arg CreateTaskTypeParams) (TaskType, error)
	CreateWorkerToken(ctx context.Context, arg CreateWorkerTokenParams) (WorkerToken, error)
	GetJob(ctx context.Context, arg GetJobParams) (Job, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetTaskType(ctx context.Context, arg GetTaskTypeParams) (TaskType, error)
	GetTaskTypeByKey(ctx context.Context, arg GetTaskTypeByKeyParams) (TaskType, error)
	ListJobEvents(ctx context.Context, arg ListJobEventsParams) ([]JobEvent, error)
	ListJobLogs(ctx context.Context, arg ListJobLogsParams) ([]JobLog, error)
	ListJobsByProject(ctx context.Context, arg ListJobsByProjectParams) ([]Job, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsByTenant(ctx context.Context, tenantID string) ([]Project, error)
	ListTaskTypesByProject(ctx context.Context, projectID pgtype.UUID) ([]TaskType, error)
	ListWorkerTokensByProject(ctx context.Context, projectID pgtype.UUID) ([]ListWorkerTokensByProjectRow, error)
	ProjectTenantID(ctx context.Context, id pgtype.UUID) (string, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
