// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  project_id,
  task_type_id,
  task_key,
  source,
  external_user_hash,
  status,
  priority,
  input_json,
  encrypted_payload_json,
  run_at,
  max_retry,
  lease_sec,
  timeout_sec,
  worker_pool_id,
  required_worker_tags,
  task_type_revision
)
VALUES (
  $1,
  $2,
  $3,
  COALESCE($4, 'admin'),
  COALESCE($5, ''),
  $6,
  COALESCE($7, 0),
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  COALESCE($15, ARRAY[]::text[]),
  $16
)
RETURNING id, project_id, task_type_id, task_key, source, status, priority, input_json, encrypted_payload_json, result_json, encrypted_result_json, progress, run_at, attempt_count, max_retry, lease_sec, timeout_sec, worker_pool_id, required_worker_tags, cancel_requested, error_code, error_message, created_at, updated_at, started_at, finished_at, output_schema_json, storage_enabled, allow_encrypted_result, task_type_revision, external_user_hash
`

type CreateJobParams struct {
	ProjectID            pgtype.UUID        `json:"project_id"`
	TaskTypeID           pgtype.UUID        `json:"task_type_id"`
	TaskKey              string             `json:"task_key"`
	Source               interface{}        `json:"source"`
	ExternalUserHash     interface{}        `json:"external_user_hash"`
	Status               string             `json:"status"`
	Priority             interface{}        `json:"priority"`
	InputJson            []byte             `json:"input_json"`
	EncryptedPayloadJson []byte             `json:"encrypted_payload_json"`
	RunAt                pgtype.Timestamptz `json:"run_at"`
	MaxRetry             int32              `json:"max_retry"`
	LeaseSec             int32              `json:"lease_sec"`
	TimeoutSec           int32              `json:"timeout_sec"`
	WorkerPoolID         pgtype.UUID        `json:"worker_pool_id"`
	RequiredWorkerTags   interface{}        `json:"required_worker_tags"`
	TaskTypeRevision     int32              `json:"task_type_revision"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ProjectID,
		arg.TaskTypeID,
		arg.TaskKey,
		arg.Source,
		arg.ExternalUserHash,
		arg.Status,
		arg.Priority,
		arg.InputJson,
		arg.EncryptedPayloadJson,
		arg.RunAt,
		arg.MaxRetry,
		arg.LeaseSec,
		arg.TimeoutSec,
		arg.WorkerPoolID,
		arg.RequiredWorkerTags,
		arg.TaskTypeRevision,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskTypeID,
		&i.TaskKey,
		&i.Source,
		&i.Status,
		&i.Priority,
		&i.InputJson,
		&i.EncryptedPayloadJson,
		&i.ResultJson,
		&i.EncryptedResultJson,
		&i.Progress,
		&i.RunAt,
		&i.AttemptCount,
		&i.MaxRetry,
		&i.LeaseSec,
		&i.TimeoutSec,
		&i.WorkerPoolID,
		&i.RequiredWorkerTags,
		&i.CancelRequested,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OutputSchemaJson,
		&i.StorageEnabled,
		&i.AllowEncryptedResult,
		&i.TaskTypeRevision,
		&i.ExternalUserHash,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, created_by_user_id, name, slug, settings_json)
VALUES (
  $1,
  $2,
  $3,
  $4,
  COALESCE($5, '{}'::jsonb)
)
RETURNING id, tenant_id, created_by_user_id, name, slug, status, settings_json, created_at, updated_at
`

type CreateProjectParams struct {
	TenantID        string      `json:"tenant_id"`
	CreatedByUserID string      `json:"created_by_user_id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	SettingsJson    interface{} `json:"settings_json"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.CreatedByUserID,
		arg.Name,
		arg.Slug,
		arg.SettingsJson,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskType = `-- name: CreateTaskType :one
INSERT INTO task_types (
  project_id,
  task_key,
  name,
  description,
  input_schema_json,
  output_schema_json,
  required_worker_tags,
  worker_pool_id,
  max_concurrent_jobs,
  max_queue_length,
  max_jobs_per_pull,
  lease_sec,
  timeout_sec,
  max_retry,
  retry_backoff_sec,
  producer_enabled,
  callbacks_enabled,
  scheduler_enabled,
  storage_enabled,
  allow_encrypted_payload,
  allow_encrypted_result
)
VALUES (
  $1,
  $2,
  $3,
  COALESCE($4, ''),
  COALESCE($5, '{}'::jsonb),
  COALESCE($6, '{}'::jsonb),
  COALESCE($7, ARRAY[]::text[]),
  $8,
  $9,
  $10,
  COALESCE($11, 1),
  COALESCE($12, 120),
  COALESCE($13, 600),
  COALESCE($14, 0),
  COALESCE($15, 0),
  COALESCE($16, false),
  COALESCE($17, false),
  COALESCE($18, false),
  COALESCE($19, false),
  COALESCE($20, false),
  COALESCE($21, false)
)
RETURNING id, project_id, task_key, name, description, input_schema_json, output_schema_json, required_worker_tags, worker_pool_id, max_concurrent_jobs, max_queue_length, max_jobs_per_pull, lease_sec, timeout_sec, max_retry, producer_enabled, callbacks_enabled, scheduler_enabled, storage_enabled, allow_encrypted_payload, allow_encrypted_result, status, created_at, updated_at, retry_backoff_sec, contract_revision
`

type CreateTaskTypeParams struct {
	ProjectID             pgtype.UUID `json:"project_id"`
	TaskKey               string      `json:"task_key"`
	Name                  string      `json:"name"`
	Description           interface{} `json:"description"`
	InputSchemaJson       interface{} `json:"input_schema_json"`
	OutputSchemaJson      interface{} `json:"output_schema_json"`
	RequiredWorkerTags    interface{} `json:"required_worker_tags"`
	WorkerPoolID          pgtype.UUID `json:"worker_pool_id"`
	MaxConcurrentJobs     pgtype.Int4 `json:"max_concurrent_jobs"`
	MaxQueueLength        pgtype.Int4 `json:"max_queue_length"`
	MaxJobsPerPull        interface{} `json:"max_jobs_per_pull"`
	LeaseSec              interface{} `json:"lease_sec"`
	TimeoutSec            interface{} `json:"timeout_sec"`
	MaxRetry              interface{} `json:"max_retry"`
	RetryBackoffSec       interface{} `json:"retry_backoff_sec"`
	ProducerEnabled       interface{} `json:"producer_enabled"`
	CallbacksEnabled      interface{} `json:"callbacks_enabled"`
	SchedulerEnabled      interface{} `json:"scheduler_enabled"`
	StorageEnabled        interface{} `json:"storage_enabled"`
	AllowEncryptedPayload interface{} `json:"allow_encrypted_payload"`
	AllowEncryptedResult  interface{} `json:"allow_encrypted_result"`
}

func (q *Queries) CreateTaskType(ctx context.Context, arg CreateTaskTypeParams) (TaskType, error) {
	row := q.db.QueryRow(ctx, createTaskType,
		arg.ProjectID,
		arg.TaskKey,
		arg.Name,
		arg.Description,
		arg.InputSchemaJson,
		arg.OutputSchemaJson,
		arg.RequiredWorkerTags,
		arg.WorkerPoolID,
		arg.MaxConcurrentJobs,
		arg.MaxQueueLength,
		arg.MaxJobsPerPull,
		arg.LeaseSec,
		arg.TimeoutSec,
		arg.MaxRetry,
		arg.RetryBackoffSec,
		arg.ProducerEnabled,
		arg.CallbacksEnabled,
		arg.SchedulerEnabled,
		arg.StorageEnabled,
		arg.AllowEncryptedPayload,
		arg.AllowEncryptedResult,
	)
	var i TaskType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskKey,
		&i.Name,
		&i.Description,
		&i.InputSchemaJson,
		&i.OutputSchemaJson,
		&i.RequiredWorkerTags,
		&i.WorkerPoolID,
		&i.MaxConcurrentJobs,
		&i.MaxQueueLength,
		&i.MaxJobsPerPull,
		&i.LeaseSec,
		&i.TimeoutSec,
		&i.MaxRetry,
		&i.ProducerEnabled,
		&i.CallbacksEnabled,
		&i.SchedulerEnabled,
		&i.StorageEnabled,
		&i.AllowEncryptedPayload,
		&i.AllowEncryptedResult,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryBackoffSec,
		&i.ContractRevision,
	)
	return i, err
}

const createWorkerToken = `-- name: CreateWorkerToken :one
INSERT INTO worker_tokens (
  project_id,
  name,
  token_hash,
  scopes,
  allowed_task_keys,
  allowed_worker_pool_ids,
  allowed_tags,
  max_concurrent_jobs,
  expires_at
)
VALUES (
  $1,
  $2,
  $3,
  COALESCE($4, ARRAY['worker']::text[]),
  COALESCE($5, ARRAY[]::text[]),
  COALESCE($6, ARRAY[]::uuid[]),
  COALESCE($7, ARRAY[]::text[]),
  $8,
  $9
)
RETURNING id, project_id, name, token_hash, scopes, allowed_task_keys, allowed_worker_pool_ids, allowed_tags, max_concurrent_jobs, status, last_used_at, created_at, revoked_at, expires_at
`

type CreateWorkerTokenParams struct {
	ProjectID            pgtype.UUID        `json:"project_id"`
	Name                 string             `json:"name"`
	TokenHash            string             `json:"token_hash"`
	Scopes               interface{}        `json:"scopes"`
	AllowedTaskKeys      interface{}        `json:"allowed_task_keys"`
	AllowedWorkerPoolIds interface{}        `json:"allowed_worker_pool_ids"`
	AllowedTags          interface{}        `json:"allowed_tags"`
	MaxConcurrentJobs    pgtype.Int4        `json:"max_concurrent_jobs"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateWorkerToken(ctx context.Context, arg CreateWorkerTokenParams) (WorkerToken, error) {
	row := q.db.QueryRow(ctx, createWorkerToken,
		arg.ProjectID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.AllowedTaskKeys,
		arg.AllowedWorkerPoolIds,
		arg.AllowedTags,
		arg.MaxConcurrentJobs,
		arg.ExpiresAt,
	)
	var i WorkerToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.AllowedTaskKeys,
		&i.AllowedWorkerPoolIds,
		&i.AllowedTags,
		&i.MaxConcurrentJobs,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, project_id, task_type_id, task_key, source, status, priority, input_json, encrypted_payload_json, result_json, encrypted_result_json, progress, run_at, attempt_count, max_retry, lease_sec, timeout_sec, worker_pool_id, required_worker_tags, cancel_requested, error_code, error_message, created_at, updated_at, started_at, finished_at, output_schema_json, storage_enabled, allow_encrypted_result, task_type_revision, external_user_hash
FROM jobs
WHERE id = $1
  AND project_id = $2
`

type GetJobParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.ProjectID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskTypeID,
		&i.TaskKey,
		&i.Source,
		&i.Status,
		&i.Priority,
		&i.InputJson,
		&i.EncryptedPayloadJson,
		&i.ResultJson,
		&i.EncryptedResultJson,
		&i.Progress,
		&i.RunAt,
		&i.AttemptCount,
		&i.MaxRetry,
		&i.LeaseSec,
		&i.TimeoutSec,
		&i.WorkerPoolID,
		&i.RequiredWorkerTags,
		&i.CancelRequested,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OutputSchemaJson,
		&i.StorageEnabled,
		&i.AllowEncryptedResult,
		&i.TaskTypeRevision,
		&i.ExternalUserHash,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, created_by_user_id, name, slug, status, settings_json, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskType = `-- name: GetTaskType :one
SELECT id, project_id, task_key, name, description, input_schema_json, output_schema_json, required_worker_tags, worker_pool_id, max_concurrent_jobs, max_queue_length, max_jobs_per_pull, lease_sec, timeout_sec, max_retry, producer_enabled, callbacks_enabled, scheduler_enabled, storage_enabled, allow_encrypted_payload, allow_encrypted_result, status, created_at, updated_at, retry_backoff_sec, contract_revision
FROM task_types
WHERE id = $1
  AND project_id = $2
`

type GetTaskTypeParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetTaskType(ctx context.Context, arg GetTaskTypeParams) (TaskType, error) {
	row := q.db.QueryRow(ctx, getTaskType, arg.ID, arg.ProjectID)
	var i TaskType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskKey,
		&i.Name,
		&i.Description,
		&i.InputSchemaJson,
		&i.OutputSchemaJson,
		&i.RequiredWorkerTags,
		&i.WorkerPoolID,
		&i.MaxConcurrentJobs,
		&i.MaxQueueLength,
		&i.MaxJobsPerPull,
		&i.LeaseSec,
		&i.TimeoutSec,
		&i.MaxRetry,
		&i.ProducerEnabled,
		&i.CallbacksEnabled,
		&i.SchedulerEnabled,
		&i.StorageEnabled,
		&i.AllowEncryptedPayload,
		&i.AllowEncryptedResult,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryBackoffSec,
		&i.ContractRevision,
	)
	return i, err
}

const getTaskTypeByKey = `-- name: GetTaskTypeByKey :one
SELECT id, project_id, task_key, name, description, input_schema_json, output_schema_json, required_worker_tags, worker_pool_id, max_concurrent_jobs, max_queue_length, max_jobs_per_pull, lease_sec, timeout_sec, max_retry, producer_enabled, callbacks_enabled, scheduler_enabled, storage_enabled, allow_encrypted_payload, allow_encrypted_result, status, created_at, updated_at, retry_backoff_sec, contract_revision
FROM task_types
WHERE project_id = $1
  AND task_key = $2
  AND status = 'active'
`

type GetTaskTypeByKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TaskKey   string      `json:"task_key"`
}

func (q *Queries) GetTaskTypeByKey(ctx context.Context, arg GetTaskTypeByKeyParams) (TaskType, error) {
	row := q.db.QueryRow(ctx, getTaskTypeByKey, arg.ProjectID, arg.TaskKey)
	var i TaskType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskKey,
		&i.Name,
		&i.Description,
		&i.InputSchemaJson,
		&i.OutputSchemaJson,
		&i.RequiredWorkerTags,
		&i.WorkerPoolID,
		&i.MaxConcurrentJobs,
		&i.MaxQueueLength,
		&i.MaxJobsPerPull,
		&i.LeaseSec,
		&i.TimeoutSec,
		&i.MaxRetry,
		&i.ProducerEnabled,
		&i.CallbacksEnabled,
		&i.SchedulerEnabled,
		&i.StorageEnabled,
		&i.AllowEncryptedPayload,
		&i.AllowEncryptedResult,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryBackoffSec,
		&i.ContractRevision,
	)
	return i, err
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT id, project_id, job_id, worker_job_id, event_type, message, metadata_json, created_at
FROM job_events
WHERE project_id = $1
  AND job_id = $2
ORDER BY created_at ASC
`

type ListJobEventsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	JobID     pgtype.UUID `json:"job_id"`
}

func (q *Queries) ListJobEvents(ctx context.Context, arg ListJobEventsParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEvents, arg.ProjectID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEvent
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.WorkerJobID,
			&i.EventType,
			&i.Message,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobLogs = `-- name: ListJobLogs :many
SELECT id, project_id, job_id, worker_job_id, level, message, metadata_json, message_bytes, created_at
FROM job_logs
WHERE project_id = $1
  AND job_id = $2
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type ListJobLogsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	JobID     pgtype.UUID `json:"job_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListJobLogs(ctx context.Context, arg ListJobLogsParams) ([]JobLog, error) {
	rows, err := q.db.Query(ctx, listJobLogs,
		arg.ProjectID,
		arg.JobID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobLog
	for rows.Next() {
		var i JobLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.WorkerJobID,
			&i.Level,
			&i.Message,
			&i.MetadataJson,
			&i.MessageBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByProject = `-- name: ListJobsByProject :many
SELECT id, project_id, task_type_id, task_key, source, status, priority, input_json, encrypted_payload_json, result_json, encrypted_result_json, progress, run_at, attempt_count, max_retry, lease_sec, timeout_sec, worker_pool_id, required_worker_tags, cancel_requested, error_code, error_message, created_at, updated_at, started_at, finished_at, output_schema_json, storage_enabled, allow_encrypted_result, task_type_revision, external_user_hash
FROM jobs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListJobsByProject(ctx context.Context, arg ListJobsByProjectParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskTypeID,
			&i.TaskKey,
			&i.Source,
			&i.Status,
			&i.Priority,
			&i.InputJson,
			&i.EncryptedPayloadJson,
			&i.ResultJson,
			&i.EncryptedResultJson,
			&i.Progress,
			&i.RunAt,
			&i.AttemptCount,
			&i.MaxRetry,
			&i.LeaseSec,
			&i.TimeoutSec,
			&i.WorkerPoolID,
			&i.RequiredWorkerTags,
			&i.CancelRequested,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OutputSchemaJson,
			&i.StorageEnabled,
			&i.AllowEncryptedResult,
			&i.TaskTypeRevision,
			&i.ExternalUserHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, created_by_user_id, name, slug, status, settings_json, created_at, updated_at
FROM projects
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CreatedByUserID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.SettingsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTenant = `-- name: ListProjectsByTenant :many
SELECT id, tenant_id, created_by_user_id, name, slug, status, settings_json, created_at, updated_at
FROM projects
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByTenant(ctx context.Context, tenantID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CreatedByUserID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.SettingsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTypesByProject = `-- name: ListTaskTypesByProject :many
SELECT id, project_id, task_key, name, description, input_schema_json, output_schema_json, required_worker_tags, worker_pool_id, max_concurrent_jobs, max_queue_length, max_jobs_per_pull, lease_sec, timeout_sec, max_retry, producer_enabled, callbacks_enabled, scheduler_enabled, storage_enabled, allow_encrypted_payload, allow_encrypted_result, status, created_at, updated_at, retry_backoff_sec, contract_revision
FROM task_types
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTaskTypesByProject(ctx context.Context, projectID pgtype.UUID) ([]TaskType, error) {
	rows, err := q.db.Query(ctx, listTaskTypesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskType
	for rows.Next() {
		var i TaskType
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskKey,
			&i.Name,
			&i.Description,
			&i.InputSchemaJson,
			&i.OutputSchemaJson,
			&i.RequiredWorkerTags,
			&i.WorkerPoolID,
			&i.MaxConcurrentJobs,
			&i.MaxQueueLength,
			&i.MaxJobsPerPull,
			&i.LeaseSec,
			&i.TimeoutSec,
			&i.MaxRetry,
			&i.ProducerEnabled,
			&i.CallbacksEnabled,
			&i.SchedulerEnabled,
			&i.StorageEnabled,
			&i.AllowEncryptedPayload,
			&i.AllowEncryptedResult,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryBackoffSec,
			&i.ContractRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerTokensByProject = `-- name: ListWorkerTokensByProject :many
SELECT id, project_id, name, scopes, allowed_task_keys, allowed_worker_pool_ids, allowed_tags, max_concurrent_jobs, status, last_used_at, created_at, revoked_at, expires_at
FROM worker_tokens
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListWorkerTokensByProjectRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	Name                 string             `json:"name"`
	Scopes               []string           `json:"scopes"`
	AllowedTaskKeys      []string           `json:"allowed_task_keys"`
	AllowedWorkerPoolIds []pgtype.UUID      `json:"allowed_worker_pool_ids"`
	AllowedTags          []string           `json:"allowed_tags"`
	MaxConcurrentJobs    pgtype.Int4        `json:"max_concurrent_jobs"`
	Status               string             `json:"status"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListWorkerTokensByProject(ctx context.Context, projectID pgtype.UUID) ([]ListWorkerTokensByProjectRow, error) {
	rows, err := q.db.Query(ctx, listWorkerTokensByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkerTokensByProjectRow
	for rows.Next() {
		var i ListWorkerTokensByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Scopes,
			&i.AllowedTaskKeys,
			&i.AllowedWorkerPoolIds,
			&i.AllowedTags,
			&i.MaxConcurrentJobs,
			&i.Status,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectTenantID = `-- name: ProjectTenantID :one
SELECT tenant_id
FROM projects
WHERE id = $1
`

func (q *Queries) ProjectTenantID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, projectTenantID, id)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name = COALESCE($2, name),
  slug = COALESCE($3, slug),
  status = COALESCE($4, status),
  settings_json = COALESCE($5, settings_json)
WHERE id = $1
RETURNING id, tenant_id, created_by_user_id, name, slug, status, settings_json, created_at, updated_at
`

type UpdateProjectParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	Status       string      `json:"status"`
	SettingsJson []byte      `json:"settings_json"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.SettingsJson,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
