package contracts

type TenantID string
type UserID string
type AgentID string
type AgentVersion string
type AgentRunID string
type TaskID string
type TaskEventID string
type TraceID string
type SpanID string
type DecisionID string
type ToolCallID string
type ToolResultID string
type ArtifactID string
type MemoryID string
type GroupID string
type GroupMemberID string
type KnowledgeBaseID string
type KnowledgeDocumentID string
type KnowledgeIngestionJobID string
type CrossGroupSharePolicyID string
type SkillUpdateRequestID string
type TopicID string
type ConversationThreadID string
type GroupTaskBindingID string
type AgentCapabilityID string
type AgentDraftRequestID string
type PolicySetID string
type PolicyVersionID string
type PackageVersionID string
type ProposalID string
type CanaryHitID string
type EvalSuiteID string
type EvalRunID string
type ApprovalID string
type HandoffID string
type ContextPackageID string
type ExternalTaskID string
type GovernanceProcessTemplateID string
type GovernanceProcessRunID string
type GovernanceGateRunID string
type GovernanceReviewID string
type GovernanceConflictID string
